import { Staff } from '../types/staff';

export function generateSampleData(): Staff[] {
  return [
    {
      id: '1',
      firstName: 'Dr. María',
      lastName: 'González',
      email: 'maria.gonzalez@sanatoriolatrinidad.com',
      phone: '+34 666 123 456',
      position: 'Jefe de Cardiología',
      department: 'Cardiología',
      specialty: 'Cardiología Intervencionista',
      type: 'doctor',
      status: 'active',
      hireDate: '2018-03-15',
      bio: 'Especialista en cardiología con más de 15 años de experiencia en procedimientos intervencionistas',
      avatar: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=400',
      certifications: ['Cardiología', 'Hemodinámica', 'Ecocardiografía'],
      keywords: ['corazón', 'cardiovascular', 'intervencionista']
    },
    {
      id: '2',
      firstName: 'Dr. Carlos',
      lastName: 'Rodríguez',
      email: 'carlos.rodriguez@sanatoriolatrinidad.com',
      phone: '+34 666 234 567',
      position: 'Neurocirujano',
      department: 'Neurología',
      specialty: 'Neurocirugía',
      type: 'doctor',
      status: 'active',
      hireDate: '2020-01-10',
      bio: 'Especialista en neurocirugía mínimamente invasiva con formación internacional',
      avatar: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=400',
      certifications: ['Neurocirugía', 'Cirugía Cerebral'],
      keywords: ['cerebro', 'neurología', 'cirugía']
    },
    {
      id: '3',
      firstName: 'Ana',
      lastName: 'Martín',
      email: 'ana.martin@sanatoriolatrinidad.com',
      phone: '+34 666 345 678',
      position: 'Enfermera Jefe',
      department: 'UCI',
      type: 'nurse',
      status: 'active',
      hireDate: '2019-06-20',
      bio: 'Enfermera especializada en cuidados intensivos con certificación en soporte vital avanzado',
      avatar: 'https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg?auto=compress&cs=tinysrgb&w=400',
      certifications: ['Enfermería', 'Cuidados Intensivos'],
      keywords: ['cuidados', 'intensivos', 'enfermería']
    },
    {
      id: '4',
      firstName: 'Luis',
      lastName: 'Fernández',
      email: 'luis.fernandez@sanatoriolatrinidad.com',
      phone: '+34 666 456 789',
      position: 'Administrador',
      department: 'Administración',
      type: 'administrative',
      status: 'active',
      hireDate: '2017-09-05',
      bio: 'Responsable de gestión administrativa y recursos humanos del sanatorio',
      avatar: 'https://images.pexels.com/photos/5212317/pexels-photo-5212317.jpeg?auto=compress&cs=tinysrgb&w=400',
      keywords: ['administración', 'gestión', 'recursos']
    },
    {
      id: '5',
      firstName: 'Dr. Laura',
      lastName: 'Jiménez',
      email: 'laura.jimenez@sanatoriolatrinidad.com',
      phone: '+34 666 567 890',
      position: 'Pediatra',
      department: 'Pediatría',
      specialty: 'Pediatría General',
      type: 'doctor',
      status: 'active',
      hireDate: '2021-02-14',
      bio: 'Especialista en pediatría con enfoque en medicina preventiva y desarrollo infantil',
      avatar: 'https://images.pexels.com/photos/5327921/pexels-photo-5327921.jpeg?auto=compress&cs=tinysrgb&w=400',
      certifications: ['Pediatría', 'Neonatología'],
      keywords: ['niños', 'pediatría', 'infantil']
    },
    {
      id: '6',
      firstName: 'Miguel',
      lastName: 'Torres',
      email: 'miguel.torres@sanatoriolatrinidad.com',
      phone: '+34 666 678 901',
      position: 'Técnico de Laboratorio',
      department: 'Laboratorio',
      type: 'technician',
      status: 'active',
      hireDate: '2020-11-08',
      bio: 'Técnico especializado en análisis clínicos y microbiología con certificación ISO',
      avatar: 'https://images.pexels.com/photos/5327580/pexels-photo-5327580.jpeg?auto=compress&cs=tinysrgb&w=400',
      certifications: ['Técnico de Laboratorio', 'Microbiología'],
      keywords: ['laboratorio', 'análisis', 'microbiología']
    }
  ];
}